#!/bin/bash

#Removes Inlists
rm inlist_comp_*
rm inlist_corer_*
rm inlist_corel_*
rm inlist_reduce_*
rm inlist_remove_heating_*
rm inlist_corem_*
rm inlist_irrad_*
rm inlist_evolve_*
rm inlist_heating_*
rm inlist_pre_reduce_*
rm inlist_pre_core_*
rm inlist_remove_cooling_*
rm inlist_cooling_*

#Get rid of .mod files
rm comp_*
rm corer_*
rm corel_*
rm reduce_*
rm remove_*
rm corem_*
rm heating_*
rm pre_reduce*
rm pre_core_*
rm profile_irrad*
rm profile_remove_heating*
rm profile_remove_cooling*
rm profile_evolve*
rm irrad*
rm evolve*

cd photos

rm x*

cd ..
cd LOGS

rm hist_comp_*
#rm corer_*
rm hist_corel_*
rm hist_reduce_*
rm hist_remove_*
rm hist_corem_*
rm hist_heating_*
rm hist_irrad_*
rm hist_evolve_*
rm hist_pre_core_*
rm hist_pre_reduce_*
